### ISSUE TITLE
js코테 입문

### ISSUE THREAD

**Issue by nimgnas** [nimgnas/js-algorithm-study#1]
다음일정:  화요일 오후9시

**Comment by blcklamb** [comment]
[💤컨트롤 제트](https://school.programmers.co.kr/learn/courses/30/lessons/120853)

**Comment by nimgnas** [comment]
[외계어 사전](https://school.programmers.co.kr/learn/courses/30/lessons/120869)

**Comment by blcklamb** [comment]
## 컨트롤 제트
[parseFloat, Number의 차이](https://joooing.tistory.com/entry/parseFloat-Number%EC%9D%98-%EC%B0%A8%EC%9D%B4%EC%A0%90)

## 외계어 사전
[Array.prototype.some()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some)
[Array.prototype.every()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/every)

**Comment by blcklamb** [comment]
https://github.com/nimgnas/js-algorithm-study/pull/3
