### ISSUE TITLE
🏆 8월 목표 [프로그래머스 순위 달성]

### ISSUE THREAD

**Issue by blcklamb** [nimgnas/js-algorithm-study#11]
프로그래머스 현재 순위랑 8월 내로 달성할 목표 순위를 공유합니다
아자아자 파이팅~!

![image](https://github.com/nimgnas/js-algorithm-study/assets/92101831/98ca5d4d-bdc9-4937-a758-c866aed617c2)

**Comment by blcklamb** [comment]
## 8월 1일자 순위
<img width="372" alt="image" src="https://github.com/nimgnas/js-algorithm-study/assets/92101831/5f7633e1-e349-4dc0-8aac-0dede81aec6e">

## 8월 내로 달성할 순위
🥇 15,000 위!!

**Comment by nimgnas** [comment]
## 8월 1일자 순위
<img width="325" alt="스크린샷 2023-08-01 오후 3 59 17" src="https://github.com/nimgnas/js-algorithm-study/assets/85691654/d989550e-128f-4d7d-af37-62506862adbf">

## 8월 내로 달성할 순위
🥇 25,000 위!!

**Comment by blcklamb** [comment]
> ## 8월 1일자 순위
> <img alt="image" width="372" src="https://user-images.githubusercontent.com/92101831/257430150-5f7633e1-e349-4dc0-8aac-0dede81aec6e.png">
> ## 8월 내로 달성할 순위
> 🥇 15,000 위!!

## 8월 1주차 목표 달성 완료!

<img width="368" alt="image" src="https://github.com/nimgnas/js-algorithm-study/assets/92101831/610eae3a-1e98-42dd-ba4c-f4cd89619dbb">

8월 2주차에는 25,000 위 이내가 목표입니다!

**Comment by nimgnas** [comment]
빠르다!!!

**Comment by nimgnas** [comment]
> ## 8월 1일자 순위
> <img alt="스크린샷 2023-08-01 오후 3 59 17" width="325" src="https://user-images.githubusercontent.com/85691654/257431339-d989550e-128f-4d7d-af37-62506862adbf.png">
> ## 8월 내로 달성할 순위
> 🥇 25,000 위!!

## 목표 달성 완료!
<img width="339" alt="스크린샷 2023-08-09 오전 10 35 37" src="https://github.com/nimgnas/js-algorithm-study/assets/85691654/d67bf7c8-da63-4e39-9007-ea4089b0efc1">

1일 2머쓱중
목표점수 20000등으로 변경하겠습니다!

**Comment by blcklamb** [comment]
멋져요~! 파이텡파이텡

**Comment by blcklamb** [comment]
## 8월 2주차 기록 
<img width="381" alt="image" src="https://github.com/nimgnas/js-algorithm-study/assets/92101831/2e2e3f04-8b40-47cb-93ab-08943111440b">
이번 주 내로 15,000등 갈 수 있지 않을까요!

**Comment by nimgnas** [comment]
## 8월 2주차 기록
<img width="343" alt="스크린샷 2023-08-14 오후 7 09 46" src="https://github.com/nimgnas/js-algorithm-study/assets/85691654/082e12c6-619e-4fa9-9c3e-fe028c756640">
채정님 15,000등 충분할 거 같아요!!

**Comment by blcklamb** [comment]
## 8월 3주차 기록
아쉽지만 15,000등은 달성 못하고 기록합니다아

<img width="369" alt="image" src="https://github.com/nimgnas/js-algorithm-study/assets/92101831/6e2cc3ef-116f-4ccd-9c9a-57a0d39421df">

4주차 목표: 15,000 등 달성과 lv 3 하나 풀어보기

**Comment by nimgnas** [comment]
## 8월 3주차 기록
오! 아슬아슬하게 제가 이겼습니다 후후
<img width="338" alt="스크린샷 2023-08-21 오전 11 34 35" src="https://github.com/nimgnas/js-algorithm-study/assets/85691654/6d633831-1282-43b7-8d64-068e9230d5da">
4주차 목표: 15,000 등 달성하기, lv 2 하나 풀어보기

**Comment by blcklamb** [comment]
## 목표 달성!

<img width="380" alt="image" src="https://github.com/nimgnas/js-algorithm-study/assets/92101831/aebb9c78-3c59-46db-9835-72341f0c139e">

## (업데이트) 8월 내로 달성할 순위
> 과감하게 네 자리 수! 9,000위 대 안으로 진입하기!!

![image](https://github.com/nimgnas/js-algorithm-study/assets/92101831/fccb1951-9cef-4e3d-aa45-708e4a3044bd)

**Comment by nimgnas** [comment]
헉...  저도 열심히 따라가겠읍니다🫠

**Comment by nimgnas** [comment]
## 8월 4주차 기록
<img width="330" alt="스크린샷 2023-08-28 오후 6 07 20" src="https://github.com/nimgnas/js-algorithm-study/assets/85691654/ed08143e-0360-4cbd-bc33-a3eedff292ae">

구명보트 너무 어려워요 ㅠㅠ

**Comment by blcklamb** [comment]
## 8월 4주차 기록

<img width="372" alt="image" src="https://github.com/nimgnas/js-algorithm-study/assets/92101831/9641a2b8-f922-421c-8824-339ed22e6088">

D-3
> 얼마 남지 않은 8월! 9000위 진입할 수 있을 것 같아서 8000위 찍어보는 걸로 목표

**Comment by blcklamb** [comment]
## 8월 마지막 기록
<img width="406" alt="image" src="https://github.com/nimgnas/js-algorithm-study/assets/92101831/7d8df237-148a-47a9-9597-cf47b9a30851">

최종 순위 7451위입니다~!

**Comment by nimgnas** [comment]
<img width="334" alt="스크린샷 2023-08-31 오후 7 49 55" src="https://github.com/nimgnas/js-algorithm-study/assets/85691654/72aa144b-79f6-4fba-8560-a1ecb83cea36">

헐 왜 이렇게 빨라요!! 저는 아쉽게도 다섯자리 마무리! 수고하셨습니다!
