### ISSUE TITLE
[8월 2주차 라이브 코딩]

### ISSUE THREAD

**Issue by blcklamb** [nimgnas/js-algorithm-study#17]
## [문제: 뒤에 있는 큰 수 찾기](https://school.programmers.co.kr/learn/courses/30/lessons/154539)

- 일시: 8월 11일 (금) 오후 4시 ~ 오후 5시
- 끝나고나서라도 문제를 풀게 되면 코멘트로 남겨주세요~!

**Comment by blcklamb** [comment]
<img width="642" alt="image" src="https://github.com/nimgnas/js-algorithm-study/assets/92101831/0419ccbe-5e57-41f0-ae58-4d1327426014">

**Comment by blcklamb** [comment]
## unshift(), push() 차이
[관련 링크](https://stackoverflow.com/questions/12250697/time-complexity-of-unshift-vs-push-in-javascript)

**Comment by nimgnas** [comment]
사진은 깜박하고 못 찍었지만 성공!!
