### ISSUE TITLE
[8월 2주차 라이브 코딩]

### ISSUE THREAD

**Issue by blcklamb** [nimgnas/js-algorithm-study#27]
## [명예의 전당 (1)](https://school.programmers.co.kr/learn/courses/30/lessons/138477)
- 일시: 8월 18일 (금) 오후 10시 37분 ~ 오후 11시 07분

**Comment by blcklamb** [comment]
<img width="651" alt="image" src="https://github.com/nimgnas/js-algorithm-study/assets/92101831/8b611f8f-0329-40dd-a3de-aeb9b8131d03">

## 결과
```javascript
'평균 시간: 0.545ms'
'평균 메모리: 33.712MB'
'최고 시간: 1.99ms'
'최저 시간: 0.07ms'
'최고 메모리: 34.3MB'
'최저 메모리: 33.4MB'
'시간 표준 편차: 1.543'
'메모리 표준 편차: 6.974'
```

**Comment by nimgnas** [comment]
<img width="601" alt="스크린샷 2023-08-19 오후 9 17 50" src="https://github.com/nimgnas/js-algorithm-study/assets/85691654/995d994e-fe31-4c02-82f7-0762ed1eea21">

성공!!

## 결과
메모리: 33.4 MB, 시간: 0.07 ms
