### ISSUE TITLE
🏆 9월 목표 [카카오 기출 문제 3주 커리큘럼]

### ISSUE THREAD

**Issue by blcklamb** [nimgnas/js-algorithm-study#41]
# [스터디 노션 템플릿](https://blcklamb.notion.site/blcklamb/KAKAO-BLIND-3-865b684e9a8c4385a5233ff249453ab9)

- 참여 기간: 9월 1일 ~ 9월 30일

- 각자 주별로 푼 문제를 노션 캡쳐해서 공유해요~!

**Comment by blcklamb** [comment]
<img width="181" alt="image" src="https://github.com/nimgnas/js-algorithm-study/assets/92101831/0b911e4f-a5b9-4da5-9490-9ede5072b6f7">

다음 달에는 150%는 달성해보자!

**Comment by nimgnas** [comment]
<img width="264" alt="스크린샷 2023-10-03 오전 12 21 42" src="https://github.com/nimgnas/js-algorithm-study/assets/85691654/68872da2-386d-4592-9af9-ebb035c885b7">

100% 달성해보자!
