### ISSUE TITLE
🏆 10월 목표 [프로그래머스 순위 달성]

### ISSUE THREAD

**Issue by blcklamb** [nimgnas/js-algorithm-study#55]
프로그래머스 현재 순위랑 10월 내로 달성할 목표 순위를 공유합니다!
아자아자 파이팅~!
+ 카카오 모의고사 병행해요~!

![image](https://github.com/nimgnas/js-algorithm-study/assets/92101831/fe5d7098-73f9-474f-8acc-d065e6c8999d)

**Comment by blcklamb** [comment]
## 10월 3일 자 순위
<img width="375" alt="image" src="https://github.com/nimgnas/js-algorithm-study/assets/92101831/a1b75196-750c-40c2-a25d-148620f26592">

## 11월이 되기 전까지 달성할 순위
🏆🏆🏆🏆800위 안으로 들기!🏆🏆🏆🏆

+) 프로그래머스 내의 Lv2 문제 전부 다 풀기

**Comment by nimgnas** [comment]
## 10월 3일 자 순위
<img width="336" alt="스크린샷 2023-10-03 오후 1 29 01" src="https://github.com/nimgnas/js-algorithm-study/assets/85691654/cef03d5b-bf9a-495d-8dfd-34d434457b4b">

## 11월이 되기 전까지 달성할 순위
🏆🏆🏆🏆3000위 안으로 들기!🏆🏆🏆🏆

+) 프로그래머스 내의 Lv1 문제 전부 다 풀기

**Comment by blcklamb** [comment]
## 11월 4일자 순위
<img width="360" alt="image" src="https://github.com/nimgnas/js-algorithm-study/assets/92101831/3bbf01a9-2b05-4cb6-91a4-0aeaf9439ee6">
