### ISSUE TITLE
🏆 11월 목표 

### ISSUE THREAD

**Issue by blcklamb** [nimgnas/js-algorithm-study#74]
각자 11월동안 달성할 목표를 자유롭게 댓글로 남겨주세요.
12월 1주차에 달성 여부를 확인합니다!

![image](https://github.com/nimgnas/js-algorithm-study/assets/92101831/43819218-88a4-4eaf-a2a2-15e53d189e16)

**Comment by blcklamb** [comment]
### [2023 KAKAO BLIND RECRUITMENT 기출](https://school.programmers.co.kr/learn/challenges?order=acceptance_asc&languages=javascript&page=1&partIds=37527) 도장 깨기

<img width="657" alt="image" src="https://github.com/nimgnas/js-algorithm-study/assets/92101831/d057fa7f-33cf-4c2c-80ab-3933308620c5">

**Comment by nimgnas** [comment]
- 프로그래머스 레벨1 전부 다 풀기
- 레벨2 이상 카카오문제 5개!
<img width="834" alt="스크린샷 2023-11-04 오전 11 05 57" src="https://github.com/nimgnas/js-algorithm-study/assets/85691654/b6a5e324-a888-4448-852e-d4b07f53f5b6">

**Comment by zwonkim** [comment]
**프로그래머스 레벨1 전부 다 풀기**

<img width="851" alt="스크린샷 2023-11-04 오전 11 07 27" src="https://github.com/nimgnas/js-algorithm-study/assets/103507999/b38ee803-075f-4aac-810d-48f44977ec5d">
